As a capstone to this fundamentals course, prepare an Analytic Report and Research Proposal on a dataset of your choosing. Your Report should accomplish these three goals:

    Describe your dataset. Describe and explore your dataset in the initial section of your Report. What does your data contain and what is its background? Where does it come from? Why is it interesting or significant? Conduct summary statistics and produce visualizations for the particular variables from the dataset that you will use.

    Ask and answer analytic questions. Ask three analytic questions and answer each one with a combination of statistics and visualizations. These analytic questions can focus on individuals behaviors or comparisons of the population.

    Propose further research. Lastly, make a proposal for a realistic future research project on this dataset that would use some data science techniques you'd like to learn in the bootcamp. Just like your earlier questions, your research proposal should present one or more clear questions. Then you should describe the techniques you would apply in order to arrive at an answer.

Report guidelines

Keep these guidelines in mind as you draft your Report:

    Length. Your Report should be three to five pages long with visualizations. Short and clear is better than long and opaque.
    Structure. Pay attention to the narrative structure of your Report. Each section should flow into the next and make a logical, readable text. Don't simply create a list of bullet points or present code without explanation. 
    
    
    
    http://insideairbnb.com/get-the-data.html
    
    This kaggle dataset might be better, but it's for Seattle specifically from 2016: https://www.kaggle.com/airbnb/seattle#listings.csv

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

%matplotlib inline

In [2]:
df = pd.read_csv('airbnb_listings.csv')
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,7893,North Williams 2brm Home,21489,Jesse,NaN,Piedmont,45.575479,-122.666777,Entire home/apt,175,3,2,8/12/2014,0.02,1,35
1,12899,"Alberta Arts 2 bedroom suite, charming 1906 house",49682,Ali And David,NaN,Concordia,45.564010,-122.634717,Private room,65,2,500,10/21/2018,4.67,1,303
2,16688,"Beautiful condo in downtown Pearl, NW Portland",64840,Ashish,NaN,Pearl,45.525418,-122.685566,Entire home/apt,275,2,44,11/4/2018,2.37,1,340
3,25200,Flamenco Dream :: hip mississippi ave.,104038,Garden,NaN,Humboldt,45.556750,-122.677839,Private room,49,7,34,10/18/2018,0.33,6,180
4,26203,Bluebird @ hip mississippi ave,104038,Garden,NaN,Humboldt,45.556965,-122.675656,Private room,49,3,28,9/30/2018,0.27,6,167

In [3]:
df.describe()

,id,host_id,neighbourhood_group,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,5.317000e+03,5.317000e+03,0.0,5317.000000,5317.000000,5317.000000,5317.000000,5317.000000,4877.000000,5317.000000,5317.000000
mean,1.531575e+07,4.244948e+07,NaN,45.527711,-122.648023,117.008275,4.221930,60.934173,3.013443,2.123190,144.244123
std,8.481055e+06,5.331177e+07,NaN,0.033481,0.046692,156.226618,10.049577,81.961679,2.920180,4.193996,127.974824
min,7.893000e+03,2.531000e+03,NaN,45.433945,-122.833981,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,7.959145e+06,5.192007e+06,NaN,45.504863,-122.680211,65.000000,1.000000,6.000000,0.780000,1.000000,22.000000
50%,1.625721e+07,1.926291e+07,NaN,45.526658,-122.649032,90.000000,2.000000,29.000000,2.380000,1.000000,115.000000
75%,2.188217e+07,5.560689e+07,NaN,45.555758,-122.621381,129.000000,2.000000,84.000000,4.450000,2.000000,268.000000
max,2.986167e+07,2.240317e+08,NaN,45.611885,-122.483763,8400.000000,222.000000,865.000000,58.160000,41.000000,365.000000

In [5]:
df = df.drop(columns=['neighbourhood_group', 'name', 'last_review'])

In [6]:
df.head()

,id,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
0,7893,21489,Jesse,Piedmont,45.575479,-122.666777,Entire home/apt,175,3,2,0.02,1,35
1,12899,49682,Ali And David,Concordia,45.564010,-122.634717,Private room,65,2,500,4.67,1,303
2,16688,64840,Ashish,Pearl,45.525418,-122.685566,Entire home/apt,275,2,44,2.37,1,340
3,25200,104038,Garden,Humboldt,45.556750,-122.677839,Private room,49,7,34,0.33,6,180
4,26203,104038,Garden,Humboldt,45.556965,-122.675656,Private room,49,3,28,0.27,6,167

theme: report for someone wanting to build a side income renting out airbnb in Portland, OR
-  could consider looking at monthly rental prices in the area as well, to see if airbnb is more profitable than renting, data here: https://www.apartmentlist.com/rentonomics/rental-price-data/
problem: not finding data with resolution better than just the city of Portland. can i even use this source? they have location as portland OR yet list as NY state, can I trust?
1. how much can one expect to make renting vs airbnb?
2. how much does it cost to pay off an apartment/house, how long would it take to pay off property with airbnb rentals?
3. links between: neighborhood and price (are room types confounding?), number of reviews//reviews per month an price, room type and price, availability over the course of a year and price. aka how can one maximize their profits on airbnb?

In [8]:
rent = pd.read_csv('Apartment-Rent-Data-City_2018-10.csv')
rent.head()

,Location,Location_Type,State,Bedroom_Size,Price_2014_01,Price_2014_02,Price_2014_03,Price_2014_04,Price_2014_05,Price_2014_06,...,Price_2018_01,Price_2018_02,Price_2018_03,Price_2018_04,Price_2018_05,Price_2018_06,Price_2018_07,Price_2018_08,Price_2018_09,Price_2018_10
0,"New York, NY",City,NY,Studio,1780.0,1778.0,1781.0,1786.0,1794.0,1802.0,...,1863.0,1859.0,1861.0,1866.0,1883.0,1905.0,1899.0,1896.0,1895.0,1908
1,"New York, NY",City,NY,1br,1976.0,1975.0,1978.0,1983.0,1992.0,2001.0,...,2069.0,2065.0,2066.0,2073.0,2091.0,2115.0,2108.0,2106.0,2104.0,2119
2,"New York, NY",City,NY,2br,2354.0,2352.0,2356.0,2362.0,2373.0,2384.0,...,2465.0,2460.0,2462.0,2469.0,2491.0,2520.0,2512.0,2509.0,2506.0,2524
3,"New York, NY",City,NY,3br,3036.0,3033.0,3038.0,3046.0,3060.0,3074.0,...,3178.0,3172.0,3174.0,3183.0,3211.0,3249.0,3239.0,3235.0,3232.0,3255
4,"New York, NY",City,NY,4br,3381.0,3378.0,3383.0,3392.0,3407.0,3424.0,...,3540.0,3532.0,3535.0,3546.0,3577.0,3619.0,3607.0,3602.0,3599.0,3625

In [25]:
portland_rent = rent[rent['Location'] == 'Portland, OR']
portland_rent.head()
portland_rent.describe()

,Price_2014_01,Price_2014_02,Price_2014_03,Price_2014_04,Price_2014_05,Price_2014_06,Price_2014_07,Price_2014_08,Price_2014_09,Price_2014_10,...,Price_2018_01,Price_2018_02,Price_2018_03,Price_2018_04,Price_2018_05,Price_2018_06,Price_2018_07,Price_2018_08,Price_2018_09,Price_2018_10
count,6600.000000,6535.000000,6515.000000,6650.000000,6530.000000,6520.000000,6215.000000,6425.000000,6390.000000,6410.000000,...,6080.000000,6590.000000,6650.000000,6760.000000,6815.000000,6725.000000,6910.000000,6995.000000,7050.000000,7155.000000
mean,1294.947424,1301.123336,1304.582195,1309.019248,1321.730475,1320.368252,1347.594368,1333.548482,1336.972144,1338.531357,...,1523.814309,1500.870561,1494.929925,1494.821598,1504.725752,1510.761933,1508.813025,1505.057756,1501.404965,1499.754997
std,685.128370,690.587546,695.547811,702.247807,710.891721,713.906096,732.320704,733.165447,737.134400,737.021292,...,865.906318,856.696032,856.879064,857.895793,868.017105,875.097105,873.617148,872.621427,872.729332,870.107145
min,403.000000,399.000000,367.000000,366.000000,364.000000,364.000000,372.000000,377.000000,379.000000,373.000000,...,417.000000,413.000000,303.000000,303.000000,303.000000,302.000000,303.000000,303.000000,303.000000,303.000000
25%,817.000000,820.000000,821.000000,823.000000,829.000000,827.000000,841.000000,833.000000,833.250000,834.000000,...,936.000000,923.000000,918.000000,914.750000,920.000000,921.000000,920.000000,918.000000,914.000000,914.500000
50%,1132.000000,1137.000000,1139.000000,1142.000000,1150.500000,1147.000000,1174.000000,1152.000000,1154.000000,1158.000000,...,1305.000000,1283.000000,1279.000000,1278.000000,1285.000000,1287.000000,1287.500000,1283.000000,1280.000000,1279.000000
75%,1557.250000,1565.000000,1566.500000,1569.000000,1586.000000,1586.000000,1621.500000,1597.000000,1600.000000,1605.750000,...,1839.000000,1813.750000,1807.000000,1809.250000,1816.000000,1822.000000,1824.750000,1819.000000,1814.000000,1806.000000
max,7915.000000,7944.000000,8020.000000,7967.000000,7921.000000,7872.000000,7932.000000,7983.000000,8038.000000,8070.000000,...,8600.000000,8601.000000,8598.000000,8668.000000,8704.000000,8765.000000,8767.000000,8779.000000,8755.000000,8755.000000

In [26]:
portland_rent

,Location,Location_Type,State,Bedroom_Size,Price_2014_01,Price_2014_02,Price_2014_03,Price_2014_04,Price_2014_05,Price_2014_06,...,Price_2018_01,Price_2018_02,Price_2018_03,Price_2018_04,Price_2018_05,Price_2018_06,Price_2018_07,Price_2018_08,Price_2018_09,Price_2018_10
0,"Portland, OR",City,NY,Studio,1780.0,1778.0,1781.0,1786.0,1794.0,1802.0,...,1863.0,1859.0,1861.0,1866.0,1883.0,1905.0,1899.0,1896.0,1895.0,1908
1,"Portland, OR",City,NY,1br,1976.0,1975.0,1978.0,1983.0,1992.0,2001.0,...,2069.0,2065.0,2066.0,2073.0,2091.0,2115.0,2108.0,2106.0,2104.0,2119
2,"Portland, OR",City,NY,2br,2354.0,2352.0,2356.0,2362.0,2373.0,2384.0,...,2465.0,2460.0,2462.0,2469.0,2491.0,2520.0,2512.0,2509.0,2506.0,2524
3,"Portland, OR",City,NY,3br,3036.0,3033.0,3038.0,3046.0,3060.0,3074.0,...,3178.0,3172.0,3174.0,3183.0,3211.0,3249.0,3239.0,3235.0,3232.0,3255
4,"Portland, OR",City,NY,4br,3381.0,3378.0,3383.0,3392.0,3407.0,3424.0,...,3540.0,3532.0,3535.0,3546.0,3577.0,3619.0,3607.0,3602.0,3599.0,3625
5,"Portland, OR",City,CA,Studio,957.0,961.0,964.0,969.0,972.0,975.0,...,1129.0,1133.0,1137.0,1139.0,1141.0,1143.0,1146.0,1147.0,1148.0,1148
6,"Portland, OR",City,CA,1br,1139.0,1143.0,1147.0,1153.0,1156.0,1160.0,...,1344.0,1349.0,1353.0,1355.0,1358.0,1361.0,1364.0,1366.0,1366.0,1367
7,"Portland, OR",City,CA,2br,1463.0,1469.0,1474.0,1481.0,1486.0,1491.0,...,1727.0,1733.0,1739.0,1741.0,1745.0,1748.0,1752.0,1755.0,1756.0,1756
8,"Portland, OR",City,CA,3br,1989.0,1997.0,2004.0,2013.0,2020.0,2026.0,...,2348.0,2356.0,2363.0,2367.0,2372.0,2376.0,2381.0,2385.0,2386.0,2387
9,"Portland, OR",City,CA,4br,2193.0,2201.0,2209.0,2220.0,2227.0,2234.0,...,2588.0,2598.0,2606.0,2610.0,2615.0,2620.0,2626.0,2630.0,2631.0,2632
10,"Portland, OR",City,IL,Studio,853.0,855.0,859.0,864.0,869.0,874.0,...,918.0,920.0,922.0,924.0,927.0,929.0,930.0,930.0,929.0,929
11,"Portland, OR",City,IL,1br,990.0,992.0,996.0,1003.0,1008.0,1014.0,...,1066.0,1067.0,1070.0,1072.0,1076.0,1079.0,1080.0,1080.0,1079.0,1078
12,"Portland, OR",City,IL,2br,1165.0,1167.0,1172.0,1180.0,1186.0,1193.0,...,1254.0,1256.0,1259.0,1261.0,1266.0,1269.0,1270.0,1270.0,1269.0,1268
13,"Portland, OR",City,IL,3br,1490.0,1493.0,1499.0,1509.0,1517.0,1525.0,...,1603.0,1606.0,1610.0,1613.0,1619.0,1623.0,1625.0,1625.0,1623.0,1622
14,"Portland, OR",City,IL,4br,1773.0,1776.0,1784.0,1796.0,1806.0,1815.0,...,1908.0,1911.0,1916.0,1919.0,1926.0,1931.0,1933.0,1933.0,1931.0,1930
15,"Portland, OR",City,TX,Studio,683.0,688.0,692.0,696.0,700.0,706.0,...,738.0,736.0,736.0,738.0,740.0,742.0,741.0,740.0,738.0,739
16,"Portland, OR",City,TX,1br,775.0,779.0,784.0,788.0,794.0,800.0,...,836.0,834.0,834.0,836.0,839.0,841.0,840.0,839.0,836.0,838
17,"Portland, OR",City,TX,2br,948.0,954.0,959.0,965.0,972.0,979.0,...,1024.0,1021.0,1021.0,1023.0,1026.0,1029.0,1028.0,1026.0,1024.0,1025
18,"Portland, OR",City,TX,3br,1292.0,1300.0,1308.0,1316.0,1325.0,1335.0,...,1395.0,1392.0,1392.0,1395.0,1399.0,1404.0,1402.0,1399.0,1396.0,1398
19,"Portland, OR",City,TX,4br,1642.0,1652.0,1663.0,1672.0,1683.0,1697.0,...,1773.0,1769.0,1769.0,1772.0,1778.0,1784.0,1781.0,1778.0,1774.0,1776
20,"Portland, OR",City,PA,Studio,738.0,742.0,745.0,748.0,751.0,753.0,...,813.0,809.0,810.0,812.0,816.0,819.0,817.0,817.0,816.0,817
21,"Portland, OR",City,PA,1br,876.0,881.0,884.0,887.0,891.0,894.0,...,965.0,961.0,962.0,964.0,969.0,972.0,970.0,969.0,968.0,970
22,"Portland, OR",City,PA,2br,1057.0,1064.0,1067.0,1072.0,1076.0,1080.0,...,1165.0,1160.0,1161.0,1164.0,1170.0,1173.0,1171.0,1170.0,1169.0,1172
23,"Portland, OR",City,PA,3br,1322.0,1331.0,1335.0,1341.0,1346.0,1351.0,...,1457.0,1451.0,1453.0,1456.0,1463.0,1468.0,1466.0,1464.0,1463.0,1466
24,"Portland, OR",City,PA,4br,1472.0,1481.0,1486.0,1492.0,1498.0,1503.0,...,1622.0,1615.0,1617.0,1620.0,1628.0,1633.0,1631.0,1629.0,1628.0,1631
25,"Portland, OR",City,AZ,Studio,573.0,577.0,581.0,583.0,586.0,588.0,...,677.0,679.0,682.0,683.0,686.0,688.0,691.0,693.0,695.0,697
26,"Portland, OR",City,AZ,1br,696.0,701.0,705.0,709.0,712.0,715.0,...,822.0,825.0,828.0,830.0,833.0,836.0,840.0,842.0,844.0,846
27,"Portland, OR",City,AZ,2br,867.0,874.0,879.0,883.0,887.0,890.0,...,1025.0,1028.0,1032.0,1034.0,1038.0,1042.0,1046.0,1050.0,1052.0,1054
28,"Portland, OR",City,AZ,3br,1262.0,1272.0,1279.0,1285.0,1291.0,1296.0,...,1491.0,1496.0,1501.0,1505.0,1511.0,1516.0,1522.0,1528.0,1530.0,1535
29,"Portland, OR",City,AZ,4br,1464.0,1476.0,1484.0,1491.0,1498.0,1503.0,...,1730.0,1735.0,1742.0,1746.0,1753.0,1759.0,1766.0,1772.0,1776.0,1780
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7125,"Portland, OR",City,MI,Studio,NaN,NaN,460.0,463.0,NaN,466.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,509.0,509
7126,"Portland, OR",City,MI,1br,NaN,NaN,555.0,559.0,NaN,563.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,614.0,615
7127,"Portland, OR",City,MI,2br,NaN,NaN,712.0,717.0,NaN,721.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,788.0,788
7128,"Portland, OR",City,MI,3br,NaN,NaN,938.0,944.0,NaN,950.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1038.0,1039
7129,"Portland, OR",City,MI,4br,NaN,NaN,1089.0,1096.0,NaN,1103.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1204.0,1205
7130,"Portland, OR",City,OH,Studio,490.0,490.0,490.0,490.0,492.0,496.0,...,NaN,NaN,NaN,NaN,592.0,NaN,NaN,607.0,605.0,617
7131,"Portland, OR",City,OH,1br,571.0,571.0,571.0,571.0,573.0,578.0,...,NaN,NaN,NaN,NaN,689.0,NaN,NaN,707.0,705.0,718
7132,"Portland, OR",City,OH,2br,751.0,751.0,751.0,751.0,753.0,760.0,...,NaN,NaN,NaN,NaN,906.0,NaN,NaN,930.0,927.0,944
7133,"Portland, OR",City,OH,3br,1049.0,1048.0,1048.0,1048.0,1051.0,1061.0,...,NaN,NaN,NaN,NaN,1265.0,NaN,NaN,1299.0,1294.0,1318
7134,"Portland, OR",City,OH,4br,1224.0,1224.0,1224.0,1224.0,1227.0,1239.0,...,NaN,NaN,NaN,NaN,1477.0,NaN,NaN,1516.0,1511.0,1539
7135,"Portland, OR",City,MI,Studio,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,574.0,574.0,574.0,574.0,574.0,574.0,574
7136,"Portland, OR",City,MI,1br,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,688.0,688.0,688.0,688.0,688.0,688.0,688
7137,"Portland, OR",City,MI,2br,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,903.0,903.0,903.0,903.0,903.0,903.0,903
7138,"Portland, OR",City,MI,3br,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1195.0,1195.0,1195.0,1195.0,1195.0,1195.0,1195
7139,"Portland, OR",City,MI,4br,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1296.0,1296.0,1296.0,1296.0,1296.0,1296.0,1296
7140,"Portland, OR",City,TX,Studio,763.0,763.0,766.0,768.0,770.0,770.0,...,819.0,817.0,817.0,822.0,837.0,843.0,837.0,832.0,834.0,837
7141,"Portland, OR",City,TX,1br,864.0,865.0,868.0,870.0,873.0,873.0,...,929.0,926.0,926.0,932.0,948.0,956.0,948.0,943.0,945.0,948
7142,"Portland, OR",City,TX,2br,1058.0,1058.0,1062.0,1065.0,1068.0,1068.0,...,1136.0,1133.0,1133.0,1140.0,1160.0,1170.0,1160.0,1154.0,1157.0,1160
7143,"Portland, OR",City,TX,3br,1442.0,1443.0,1448.0,1452.0,1457.0,1456.0,...,1549.0,1545.0,1545.0,1554.0,1582.0,1595.0,1582.0,1574.0,1577.0,1582
7144,"Portland, OR",City,TX,4br,1833.0,1834.0,1841.0,1846.0,1851.0,1851.0,...,1969.0,1963.0,1963.0,1976.0,2011.0,2026.0,2010.0,2000.0,2004.0,2010
7145,"Portland, OR",City,SC,Studio,717.0,706.0,705.0,707.0,708.0,708.0,...,779.0,784.0,791.0,792.0,785.0,776.0,780.0,784.0,788.0,783
7146,"Portland, OR",City,SC,1br,905.0,892.0,891.0,892.0,894.0,894.0,...,984.0,989.0,998.0,999.0,991.0,980.0,985.0,990.0,995.0,989
7147,"Portland, OR",City,SC,2br,1046.0,1030.0,1029.0,1031.0,1032.0,1033.0,...,1137.0,1143.0,1153.0,1154.0,1145.0,1132.0,1138.0,1144.0,1149.0,1142
7148,"Portland, OR",City,SC,3br,1383.0,1362.0,1360.0,1363.0,1365.0,1365.0,...,1503.0,1511.0,1525.0,1526.0,1514.0,1496.0,1505.0,1512.0,1519.0,1511
7149,"Portland, OR",City,SC,4br,1723.0,1697.0,1695.0,1698.0,1701.0,1701.0,...,1873.0,1883.0,1900.0,1902.0,1886.0,1864.0,1875.0,1884.0,1893.0,1882
7150,"Portland, OR",City,TX,Studio,825.0,820.0,818.0,818.0,824.0,NaN,...,NaN,659.0,649.0,633.0,603.0,571.0,624.0,643.0,656.0,615
7151,"Portland, OR",City,TX,1br,935.0,929.0,927.0,927.0,933.0,NaN,...,NaN,747.0,735.0,718.0,683.0,647.0,707.0,728.0,744.0,697
7152,"Portland, OR",City,TX,2br,1145.0,1137.0,1135.0,1134.0,1142.0,NaN,...,NaN,914.0,900.0,878.0,836.0,792.0,865.0,891.0,910.0,853
7153,"Portland, OR",City,TX,3br,1561.0,1550.0,1547.0,1546.0,1558.0,NaN,...,NaN,1246.0,1226.0,1198.0,1140.0,1080.0,1179.0,1215.0,1241.0,1162
7154,"Portland, OR",City,TX,4br,1983.0,1970.0,1966.0,1965.0,1979.0,NaN,...,NaN,1583.0,1559.0,1522.0,1448.0,1373.0,1499.0,1544.0,1577.0,1477

In [22]:
OR_rent = rent[rent['State'] == 'OR']
print(OR_rent)
OR_rent.describe()

          Location Location_Type State Bedroom_Size  Price_2014_01  \
140   Portland, OR          City    OR       Studio          922.0
141   Portland, OR          City    OR          1br         1026.0
142   Portland, OR          City    OR          2br         1210.0
143   Portland, OR          City    OR          3br         1762.0
144   Portland, OR          City    OR          4br         2133.0
735   Portland, OR          City    OR       Studio          569.0
736   Portland, OR          City    OR          1br          674.0
737   Portland, OR          City    OR          2br          897.0
738   Portland, OR          City    OR          3br         1300.0
739   Portland, OR          City    OR          4br         1566.0
745   Portland, OR          City    OR       Studio          535.0
746   Portland, OR          City    OR          1br          600.0
747   Portland, OR          City    OR          2br          789.0
748   Portland, OR          City    OR          3br         1148.0
749   Portland, OR          City    OR          4br         1390.0
1225  Portland, OR          City    OR       Studio          881.0
1226  Portland, OR          City    OR          1br          980.0
1227  Portland, OR          City    OR          2br         1157.0
1228  Portland, OR          City    OR          3br         1684.0
1229  Portland, OR          City    OR          4br         2038.0
1505  Portland, OR          City    OR       Studio         1040.0
1506  Portland, OR          City    OR          1br         1157.0
1507  Portland, OR          City    OR          2br         1365.0
1508  Portland, OR          City    OR          3br         1986.0
1509  Portland, OR          City    OR          4br         2404.0
1550  Portland, OR          City    OR       Studio          960.0
1551  Portland, OR          City    OR          1br         1069.0
1552  Portland, OR          City    OR          2br         1261.0
1553  Portland, OR          City    OR          3br         1835.0
1554  Portland, OR          City    OR          4br         2221.0
...            ...           ...   ...          ...            ...
5360  Portland, OR          City    OR       Studio          753.0
5361  Portland, OR          City    OR          1br          838.0
5362  Portland, OR          City    OR          2br          988.0
5363  Portland, OR          City    OR          3br         1438.0
5364  Portland, OR          City    OR          4br         1741.0
5465  Portland, OR          City    OR       Studio            NaN
5466  Portland, OR          City    OR          1br            NaN
5467  Portland, OR          City    OR          2br            NaN
5468  Portland, OR          City    OR          3br            NaN
5469  Portland, OR          City    OR          4br            NaN
5510  Portland, OR          City    OR       Studio          935.0
5511  Portland, OR          City    OR          1br         1041.0
5512  Portland, OR          City    OR          2br         1228.0
5513  Portland, OR          City    OR          3br         1787.0
5514  Portland, OR          City    OR          4br         2163.0
5850  Portland, OR          City    OR       Studio            NaN
5851  Portland, OR          City    OR          1br            NaN
5852  Portland, OR          City    OR          2br            NaN
5853  Portland, OR          City    OR          3br            NaN
5854  Portland, OR          City    OR          4br            NaN
6325  Portland, OR          City    OR       Studio            NaN
6326  Portland, OR          City    OR          1br            NaN
6327  Portland, OR          City    OR          2br            NaN
6328  Portland, OR          City    OR          3br            NaN
6329  Portland, OR          City    OR          4br            NaN
6550  Portland, OR          City    OR       Studio          932.0
6551  Portland, OR          City    OR          1br         1037.0
6552  Portland, OR          City    OR          2br         1224.0
6553  Portland, OR          City    OR          3br         1782.0
6554  Portland, OR          City    OR          4br         2156.0

      Price_2014_02  Price_2014_03  Price_2014_04  Price_2014_05  \
140           921.0          925.0          930.0          935.0
141          1025.0         1030.0         1034.0         1041.0
142          1210.0         1215.0         1220.0         1228.0
143          1761.0         1768.0         1776.0         1787.0
144          2131.0         2140.0         2150.0         2163.0
735           569.0          569.0          570.0          571.0
736           674.0          674.0          676.0          677.0
737           897.0          897.0          898.0          901.0
738          1300.0         1300.0         1302.0         1306.0
739          1566.0         1567.0         1569.0         1574.0
745           537.0          538.0          539.0          541.0
746           602.0          603.0          605.0          607.0
747           791.0          793.0          795.0          798.0
748          1151.0         1154.0         1157.0         1161.0
749          1394.0         1397.0         1401.0         1406.0
1225          885.0          888.0          893.0          900.0
1226          984.0          988.0          993.0         1001.0
1227         1161.0         1165.0         1172.0         1181.0
1228         1691.0         1696.0         1705.0         1719.0
1229         2046.0         2053.0         2064.0         2081.0
1505         1041.0         1051.0         1060.0         1065.0
1506         1158.0         1170.0         1180.0         1185.0
1507         1366.0         1380.0         1392.0         1398.0
1508         1989.0         2009.0         2026.0         2035.0
1509         2407.0         2431.0         2452.0         2464.0
1550          962.0          971.0          983.0          992.0
1551         1070.0         1080.0         1093.0         1103.0
1552         1262.0         1274.0         1290.0         1302.0
1553         1837.0         1854.0         1878.0         1895.0
1554         2224.0         2244.0         2273.0         2294.0
...             ...            ...            ...            ...
5360          754.0          759.0          762.0          770.0
5361          839.0          845.0          848.0          857.0
5362          989.0          997.0         1000.0         1011.0
5363         1440.0         1451.0         1456.0         1471.0
5364         1743.0         1756.0         1763.0         1781.0
5465            NaN            NaN          618.0          619.0
5466            NaN            NaN          651.0          652.0
5467            NaN            NaN          865.0          867.0
5468            NaN            NaN         1260.0         1263.0
5469            NaN            NaN         1444.0         1447.0
5510          935.0          942.0          953.0          963.0
5511         1041.0         1048.0         1060.0         1072.0
5512         1228.0         1236.0         1250.0         1264.0
5513         1787.0         1799.0         1820.0         1840.0
5514         2163.0         2178.0         2203.0         2227.0
5850            NaN            NaN            NaN            NaN
5851            NaN            NaN            NaN            NaN
5852            NaN            NaN            NaN            NaN
5853            NaN            NaN            NaN            NaN
5854            NaN            NaN            NaN            NaN
6325            NaN            NaN            NaN            NaN
6326            NaN            NaN            NaN            NaN
6327            NaN            NaN            NaN            NaN
6328            NaN            NaN            NaN            NaN
6329            NaN            NaN            NaN            NaN
6550          935.0          936.0          938.0          939.0
6551         1040.0         1041.0         1044.0         1045.0
6552         1227.0         1228.0         1231.0         1233.0
6553         1786.0         1788.0         1792.0         1794.0
6554         2161.0         2164.0         2169.0         2172.0

      Price_2014_06      ...        Price_2018_01  Price_2018_02  \
140           941.0      ...               1005.0         1014.0
141          1047.0      ...               1118.0         1128.0
142          1236.0      ...               1320.0         1331.0
143          1798.0      ...               1921.0         1937.0
144          2177.0      ...               2325.0         2345.0
735           573.0      ...                678.0          685.0
736           680.0      ...                804.0          812.0
737           904.0      ...               1070.0         1081.0
738          1311.0      ...               1551.0         1566.0
739          1579.0      ...               1869.0         1887.0
745           544.0      ...                723.0          732.0
746           610.0      ...                810.0          821.0
747           801.0      ...               1065.0         1079.0
748          1166.0      ...               1550.0         1571.0
749          1412.0      ...               1877.0         1902.0
1225          905.0      ...               1252.0         1256.0
1226         1007.0      ...               1393.0         1397.0
1227         1188.0      ...               1643.0         1649.0
1228         1730.0      ...               2392.0         2400.0
1229         2094.0      ...               2895.0         2905.0
1505         1069.0      ...               1508.0         1529.0
1506         1189.0      ...               1678.0         1702.0
1507         1403.0      ...               1979.0         2007.0
1508         2042.0      ...               2881.0         2922.0
1509         2471.0      ...               3487.0         3537.0
1550         1000.0      ...               1319.0         1319.0
1551         1113.0      ...               1467.0         1467.0
1552         1313.0      ...               1731.0         1731.0
1553         1911.0      ...               2520.0         2520.0
1554         2313.0      ...               3050.0         3050.0
...             ...      ...                  ...            ...
5360          773.0      ...                  NaN         1076.0
5361          860.0      ...                  NaN         1197.0
5362         1014.0      ...                  NaN         1413.0
5363         1477.0      ...                  NaN         2056.0
5364         1787.0      ...                  NaN         2489.0
5465          621.0      ...                654.0          657.0
5466          653.0      ...                689.0          692.0
5467          869.0      ...                916.0          920.0
5468         1266.0      ...               1334.0         1340.0
5469         1450.0      ...               1529.0         1535.0
5510          970.0      ...               1265.0         1266.0
5511         1080.0      ...               1407.0         1408.0
5512         1274.0      ...               1660.0         1661.0
5513         1854.0      ...               2416.0         2418.0
5514         2244.0      ...               2925.0         2927.0
5850            NaN      ...               1299.0         1313.0
5851            NaN      ...               1445.0         1461.0
5852            NaN      ...               1705.0         1724.0
5853            NaN      ...               2481.0         2509.0
5854            NaN      ...               3003.0         3037.0
6325            NaN      ...               1342.0         1339.0
6326            NaN      ...               1493.0         1490.0
6327            NaN      ...               1761.0         1757.0
6328            NaN      ...               2564.0         2558.0
6329            NaN      ...               3103.0         3096.0
6550          941.0      ...                  NaN         1393.0
6551         1047.0      ...                  NaN         1550.0
6552         1235.0      ...                  NaN         1829.0
6553         1798.0      ...                  NaN         2662.0
6554         2176.0      ...                  NaN         3222.0

      Price_2018_03  Price_2018_04  Price_2018_05  Price_2018_06  \
140          1018.0         1013.0         1010.0         1007.0
141          1132.0         1128.0         1123.0         1120.0
142          1336.0         1330.0         1325.0         1321.0
143          1945.0         1936.0         1929.0         1923.0
144          2354.0         2344.0         2335.0         2328.0
735           688.0          687.0          685.0          682.0
736           816.0          814.0          812.0          809.0
737          1086.0         1083.0         1080.0         1076.0
738          1574.0         1570.0         1566.0         1559.0
739          1896.0         1891.0         1886.0         1878.0
745           736.0          733.0          729.0          723.0
746           825.0          822.0          817.0          811.0
747          1084.0         1081.0         1074.0         1066.0
748          1578.0         1573.0         1564.0         1551.0
749          1911.0         1905.0         1893.0         1878.0
1225         1257.0         1256.0         1257.0         1258.0
1226         1399.0         1398.0         1399.0         1400.0
1227         1650.0         1649.0         1651.0         1652.0
1228         2402.0         2400.0         2403.0         2404.0
1229         2907.0         2905.0         2908.0         2910.0
1505         1537.0         1532.0         1520.0         1527.0
1506         1710.0         1704.0         1692.0         1699.0
1507         2018.0         2010.0         1996.0         2004.0
1508         2937.0         2926.0         2905.0         2917.0
1509         3555.0         3542.0         3516.0         3531.0
1550         1322.0         1325.0         1332.0         1342.0
1551         1471.0         1475.0         1482.0         1493.0
1552         1736.0         1740.0         1749.0         1761.0
1553         2527.0         2533.0         2545.0         2564.0
1554         3058.0         3065.0         3081.0         3103.0
...             ...            ...            ...            ...
5360         1077.0         1081.0         1079.0         1078.0
5361         1198.0         1203.0         1201.0         1199.0
5362         1413.0         1419.0         1416.0         1414.0
5363         2057.0         2065.0         2062.0         2059.0
5364         2490.0         2500.0         2496.0         2492.0
5465          660.0          659.0          660.0          657.0
5466          695.0          694.0          694.0          692.0
5467          924.0          923.0          924.0          920.0
5468         1345.0         1344.0         1345.0         1340.0
5469         1541.0         1540.0         1541.0         1536.0
5510         1271.0         1299.0         1308.0         1340.0
5511         1414.0         1446.0         1455.0         1491.0
5512         1669.0         1706.0         1716.0         1759.0
5513         2429.0         2483.0         2498.0         2560.0
5514         2940.0         3005.0         3024.0         3099.0
5850            NaN         1345.0         1344.0         1329.0
5851            NaN         1497.0         1495.0         1478.0
5852            NaN         1766.0         1764.0         1744.0
5853            NaN         2571.0         2568.0         2539.0
5854            NaN         3111.0         3108.0         3073.0
6325         1341.0         1349.0         1365.0         1366.0
6326         1492.0         1501.0         1519.0         1520.0
6327         1760.0         1770.0         1792.0         1794.0
6328         2562.0         2577.0         2609.0         2611.0
6329         3101.0         3119.0         3157.0         3160.0
6550         1389.0         1379.0         1358.0         1362.0
6551         1545.0         1534.0         1511.0         1515.0
6552         1823.0         1810.0         1782.0         1788.0
6553         2654.0         2635.0         2594.0         2602.0
6554         3212.0         3189.0         3140.0         3150.0

      Price_2018_07  Price_2018_08  Price_2018_09  Price_2018_10
140          1014.0         1018.0         1021.0           1015
141          1128.0         1133.0         1136.0           1129
142          1330.0         1337.0         1341.0           1333
143          1937.0         1946.0         1952.0           1940
144          2344.0         2355.0         2362.0           2348
735           688.0          692.0          696.0            692
736           815.0          821.0          825.0            820
737          1084.0         1092.0         1097.0           1091
738          1572.0         1583.0         1591.0           1581
739          1894.0         1907.0         1917.0           1905
745           732.0          738.0          742.0            736
746           821.0          827.0          832.0            825
747          1079.0         1088.0         1094.0           1084
748          1570.0         1583.0         1592.0           1578
749          1901.0         1916.0         1928.0           1911
1225         1264.0         1265.0         1268.0           1265
1226         1406.0         1407.0         1410.0           1408
1227         1659.0         1660.0         1664.0           1661
1228         2414.0         2417.0         2422.0           2418
1229         2922.0         2925.0         2932.0           2926
1505         1550.0         1560.0         1560.0           1542
1506         1725.0         1735.0         1736.0           1716
1507         2035.0         2047.0         2048.0           2024
1508         2962.0         2980.0         2981.0           2946
1509         3585.0         3607.0         3608.0           3566
1550         1345.0         1345.0         1341.0           1346
1551         1497.0         1496.0         1492.0           1498
1552         1766.0         1765.0         1760.0           1767
1553         2570.0         2570.0         2562.0           2572
1554         3111.0         3110.0         3100.0           3113
...             ...            ...            ...            ...
5360         1076.0         1079.0         1082.0           1076
5361         1198.0         1201.0         1203.0           1198
5362         1413.0         1417.0         1420.0           1413
5363         2057.0         2062.0         2067.0           2057
5364         2489.0         2496.0         2501.0           2489
5465          660.0          662.0          663.0            661
5466          695.0          697.0          698.0            696
5467          924.0          926.0          929.0            925
5468         1346.0         1349.0         1352.0           1347
5469         1542.0         1546.0         1550.0           1544
5510         1343.0         1342.0         1333.0           1351
5511         1494.0         1493.0         1483.0           1503
5512         1763.0         1761.0         1749.0           1773
5513         2566.0         2564.0         2546.0           2581
5514         3106.0         3103.0         3082.0           3124
5850         1344.0         1367.0         1382.0           1364
5851         1496.0         1521.0         1537.0           1518
5852         1764.0         1795.0         1814.0           1791
5853         2568.0         2613.0         2640.0           2607
5854         3108.0         3162.0         3195.0           3155
6325         1364.0         1364.0         1366.0           1375
6326         1518.0         1518.0         1520.0           1530
6327         1790.0         1791.0         1793.0           1805
6328         2606.0         2606.0         2610.0           2627
6329         3154.0         3155.0         3159.0           3180

,Price_2014_01,Price_2014_02,Price_2014_03,Price_2014_04,Price_2014_05,Price_2014_06,Price_2014_07,Price_2014_08,Price_2014_09,Price_2014_10,...,Price_2018_01,Price_2018_02,Price_2018_03,Price_2018_04,Price_2018_05,Price_2018_06,Price_2018_07,Price_2018_08,Price_2018_09,Price_2018_10
count,85.000000,80.00000,80.000000,85.000000,85.000000,85.000000,85.000000,85.000000,85.000000,90.000000,...,85.000000,100.000000,95.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,1263.329412,1290.78750,1297.850000,1285.647059,1235.670588,1241.129412,1249.141176,1255.988235,1263.247059,1289.200000,...,1658.529412,1660.460000,1646.368421,1670.430000,1671.770000,1675.550000,1683.970000,1689.460000,1690.860000,1687.580000
std,533.296183,539.66977,545.463805,545.896002,518.949130,521.039364,526.054274,529.810849,533.713404,542.911196,...,751.140016,747.099109,749.100511,753.559114,754.228214,758.585225,764.262455,767.681981,767.631725,765.269942
min,517.000000,519.00000,519.000000,521.000000,522.000000,526.000000,526.000000,524.000000,523.000000,525.000000,...,610.000000,610.000000,610.000000,611.000000,612.000000,614.000000,614.000000,614.000000,614.000000,614.000000
25%,881.000000,894.00000,894.750000,886.000000,857.000000,860.000000,865.000000,871.000000,878.000000,884.250000,...,1070.000000,1080.500000,1080.500000,1082.500000,1079.750000,1077.500000,1082.750000,1091.000000,1096.250000,1089.250000
50%,1172.000000,1202.00000,1214.500000,1220.000000,1185.000000,1189.000000,1196.000000,1202.000000,1204.000000,1211.500000,...,1507.000000,1509.500000,1492.000000,1516.500000,1515.000000,1517.500000,1523.000000,1531.500000,1540.500000,1531.000000
75%,1539.000000,1566.50000,1573.750000,1561.000000,1471.000000,1477.000000,1485.000000,1496.000000,1511.000000,1548.000000,...,1921.000000,1936.250000,1926.000000,1939.750000,1935.500000,1957.750000,1950.250000,1954.250000,1958.000000,1949.500000
max,2711.000000,2762.00000,2808.000000,2840.000000,2773.000000,2774.000000,2799.000000,2800.000000,2806.000000,2811.000000,...,3487.000000,3537.000000,3555.000000,3542.000000,3516.000000,3531.000000,3585.000000,3607.000000,3608.000000,3566.000000

In [24]:
OR_rent.Location.unique()

array(['Portland, OR'], dtype=object)

In [32]:
full_OR_airbnb = pd.read_csv('listings.csv.gz', compression='gzip')
full_OR_airbnb.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,requires_license,license,jurisdiction_names,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,7893,https://www.airbnb.com/rooms/7893,20181107122123,2018-11-07,North Williams 2brm Home,"Located on Williams bike corridor, some of Por...",This NE Portland 2 bedroom home is located jus...,"Located on Williams bike corridor, some of Por...",none,NaN,...,t,NaN,"{OREGON,"" MULTNOMAH"","" PORTLAND""}",f,f,flexible,f,f,1,0.02
1,12899,https://www.airbnb.com/rooms/12899,20181107122123,2018-11-07,"Alberta Arts 2 bedroom suite, charming 1906 house",Settle in to a space of your own. You'll have ...,We live in a neighborhood of beautiful gardens...,Settle in to a space of your own. You'll have ...,none,We're within walking distance of a grocery and...,...,t,14-218887-000-00-HO,"{OREGON,"" MULTNOMAH"","" PORTLAND""}",f,f,moderate,f,f,1,4.67
2,16688,https://www.airbnb.com/rooms/16688,20181107122123,2018-11-07,"Beautiful condo in downtown Pearl, NW Portland","Newly remodeled 2 bedroom (3 queen beds), 2 fu...","- Fully furnished condo with high ceilings, bi...","Newly remodeled 2 bedroom (3 queen beds), 2 fu...",none,Easily one of Portland’s most desirable neighb...,...,t,2008-190040-000-00-RS,"{OREGON,"" MULTNOMAH"","" PORTLAND""}",t,f,moderate,f,f,1,2.37
3,25200,https://www.airbnb.com/rooms/25200,20181107122123,2018-11-07,Flamenco Dream :: hip mississippi ave.,"If you are an Urban Farming pioneer, enthusias...",The large farmhouse is surrounded by magical u...,"If you are an Urban Farming pioneer, enthusias...",none,Tierra Soul is located in the fun and hip Miss...,...,t,NaN,"{OREGON,"" MULTNOMAH"","" PORTLAND""}",f,f,strict_14_with_grace_period,f,f,6,0.33
4,26203,https://www.airbnb.com/rooms/26203,20181107122123,2018-11-07,Bluebird @ hip mississippi ave,"If you are an Urban Farming pioneer, enthusias...",The large farmhouse is surrounded by magical u...,"If you are an Urban Farming pioneer, enthusias...",none,We are located in the fun and hip Mississippi ...,...,t,NaN,"{OREGON,"" MULTNOMAH"","" PORTLAND""}",f,f,strict_14_with_grace_period,f,f,6,0.27

In [33]:
full_OR_airbnb.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'experiences_offered', 'neighborhood_overview',
       'notes', 'transit', 'access', 'interaction', 'house_rules',
       'thumbnail_url', 'medium_url', 'picture_url', 'xl_picture_url',
       'host_id', 'host_url', 'host_name', 'host_since', 'host_location',
       'host_about', 'host_response_time', 'host_response_rate',
       'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url',
       'host_picture_url', 'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'street',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'city', 'state', 'zipcode', 'market',
       'smart_location', 'country_code', 'country', 'latitude', 'longitude',
       'is_location_exact', 'property_type', 'room_type', 'accommodates',
       'bathrooms', 'bedrooms', 'beds', 'bed_type', 'amenities', 'square_feet',
       'price', 'weekly_price', 'monthly_price', 'security_deposit',
       'cleaning_fee', 'guests_included', 'extra_people', 'minimum_nights',
       'maximum_nights', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'first_review', 'last_review', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'requires_license',
       'license', 'jurisdiction_names', 'instant_bookable',
       'is_business_travel_ready', 'cancellation_policy',
       'require_guest_profile_picture', 'require_guest_phone_verification',
       'calculated_host_listings_count', 'reviews_per_month'],
      dtype='object')

In [34]:
full_OR_airbnb.describe()

,id,scrape_id,thumbnail_url,medium_url,xl_picture_url,host_id,host_acceptance_rate,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,...,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,reviews_per_month
count,5.317000e+03,5.317000e+03,0.0,0.0,0.0,5.317000e+03,0.0,5312.000000,5312.000000,0.0,...,5317.000000,4846.000000,4844.000000,4843.000000,4841.000000,4842.000000,4841.000000,4841.000000,5317.000000,4877.000000
mean,1.531575e+07,2.018111e+13,NaN,NaN,NaN,4.244948e+07,NaN,12.256589,12.256589,NaN,...,60.934173,96.931077,9.880058,9.784844,9.940921,9.932879,9.790126,9.739103,2.123190,3.013443
std,8.481055e+06,8.868021e-01,NaN,NaN,NaN,5.331177e+07,NaN,114.287981,114.287981,NaN,...,81.961679,4.410958,0.426587,0.548327,0.302573,0.341687,0.477763,0.551386,4.193996,2.920180
min,7.893000e+03,2.018111e+13,NaN,NaN,NaN,2.531000e+03,NaN,0.000000,0.000000,NaN,...,0.000000,20.000000,2.000000,2.000000,5.000000,2.000000,4.000000,2.000000,1.000000,0.010000
25%,7.959145e+06,2.018111e+13,NaN,NaN,NaN,5.192007e+06,NaN,1.000000,1.000000,NaN,...,6.000000,96.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,0.780000
50%,1.625721e+07,2.018111e+13,NaN,NaN,NaN,1.926291e+07,NaN,1.000000,1.000000,NaN,...,29.000000,98.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,2.380000
75%,2.188217e+07,2.018111e+13,NaN,NaN,NaN,5.560689e+07,NaN,2.000000,2.000000,NaN,...,84.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,2.000000,4.450000
max,2.986167e+07,2.018111e+13,NaN,NaN,NaN,2.240317e+08,NaN,1305.000000,1305.000000,NaN,...,865.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,41.000000,58.160000

In [36]:
full_OR_airbnb.dropna().describe()

,id,scrape_id,thumbnail_url,medium_url,xl_picture_url,host_id,host_acceptance_rate,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,...,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,reviews_per_month
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN